### ISSUE TITLE
Add logs on file download completion and task completion

### ISSUE THREAD

**Issue by joicemjoseph** [ajinasokan/ditto#3]
I think it will be better to indicate users on download completion.

after
https://github.com/ajinasokan/ditto/blob/63aa11d608d705826b972815c3ad6d8dfe97eb98/scripts/downloader.dart#L10 

https://github.com/ajinasokan/ditto/blob/63aa11d608d705826b972815c3ad6d8dfe97eb98/scripts/downloader.dart#L14

https://github.com/ajinasokan/ditto/blob/63aa11d608d705826b972815c3ad6d8dfe97eb98/scripts/downloader.dart#L26

**Comment by ajinasokan** [comment]
Yup. That was just a rough implementation. Note that this is for devs, app doesn't do any of this. It has embedded, ready to load assets.
